### ISSUE TITLE
account-setup.md page returns an error

### ISSUE THREAD

**Issue by ejm554** [Vets-Who-Code/prework#17]
When attempting to open the account setup page in the Prework area, an 404 error appears. See screenshot.

<img width="696" alt="image" src="https://github.com/Vets-Who-Code/Prework/assets/26723535/99135843-e11b-40cb-843e-2f0ed404ccdc">

**Comment by ptenteromano** [comment]
Looks like you have the wrong url, it should be:
https://github.com/Vets-Who-Code/Prework/blob/master/account-set-up.md

The file name is `account-set-up.md`. You can always go to the root of the code in on Github and navigate the file structure there.

**Comment by jeromehardaway** [comment]
Great job helping @ptenteromano I took the time to fix the URL. Thanks to both of you.
