### ISSUE TITLE
Remove twitter requirement

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/prework#9]
Let's not make it a req for troops to be on Twitter. Let's focus on the MS ecosystem of Linkedin and Github as it's more trustworthy.

**Comment by LouisRodriguez12101815** [comment]
Isn't X formerly twitter safer now that users must pay to be verified?

**Comment by jeromehardaway** [comment]
> Isn't X formerly twitter safer now that users must pay to be verified?

No.
